export const GET_USERS_REQUEST = "GET_USERS_REQUEST" 
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS" 
export const GET_USERS_FAILURE = "GET_USERS_FAILURE" 

export const DEL_USERS_REQUEST = "DEL_USERS_REQUEST" 
export const DEL_USERS_SUCCESS = "DEL_USERS_SUCCESS" 
export const DEL_USERS_FAILURE = "DEL_USERS_FAILURE" 

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST" 
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS" 
export const ADD_USER_FAILURE = "ADD_USER_FAILURE" 

export const SET_USER_SELECTED = "SET_USER_SELECTED"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST" 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS" 
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE" 






